### PR TITLE
Strip whitespaces between range operator

### PR DESCRIPTION
**Pull request by piotrooo**
Transletes range:

```
<=   2.6.8 ||    >= 3.0.0 <= 3.0.1 || >5.0.0
```

to

```
<=2.6.8 || >=3.0.0 <=3.0.1 || >5.0.0
```

### CODE REVIEW

**Comment by jeremylong** [comment]
@piotrooo love the library! any idea when the next release will be (we have a reported issue in dependency-check that this PR resolves)?

Thanks!

**Comment by piotrooo** [comment]
I'll try to release it today since I've come back to the home. If not, I'll definitely do this tomorrow.

**Comment by piotrooo** [comment]
@jeremylong new version was just released. Should be available in the Maven Central soon.

**Comment by jeremylong** [comment]
Thanks!

**Pull request merged**
