### PR TITLE
Add forbiddenapis

### PR DESCRIPTION
**Pull request by risdenk**
Apache Solr started using semver4j (https://issues.apache.org/jira/browse/SOLR-15910) and noticed that under certain Java locales semver4j fails (https://issues.apache.org/jira/browse/SOLR-16467). Solr randomizes the locales to ensure that tests pass. This PR adds forbidden-apis (https://github.com/policeman-tools/forbidden-apis) which is a static build check for APIs that have issues. The changes in this PR use `Locale.ROOT` which will be the same everywhere. This makes sense since we just want simple strings for version comparison.

### CODE REVIEW

**Comment by piotrooo** [comment]
Many thanks! Give me couple of days to review changes.

**Comment by piotrooo** [comment]
@risdenk by default this plugin run with in a `verify` phase, now we run the `package` phase, so we don't run validation added by you. Could you change GitHub Actions as well?

**Comment by risdenk** [comment]
Moved to `mvnw verify` in github actions - 1960f974f47b305a2ac4a4bc7ff526d421a3aad9 - need to skip GPG verify since its not available in github actions.

**Comment by risdenk** [comment]
Thanks for the quick review @piotrooo - if possible would love to get this in and have a semver4j release that I can upgrade in Apache Solr to within the next few weeks.

**Comment by piotrooo** [comment]
@risdenk I don't have access to the PC. So this change must wait until I've come back from holidays (to the next monday).

**Comment by risdenk** [comment]
No worries enjoy the time off :)

**Review by piotrooo — APPROVED** [review]

**Comment by risdenk** [comment]
Thanks @piotrooo! Will update Apache Solr shortly

**Pull request merged**
